name: charted
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: "3.22.1"

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  provider: ^6.1.2
  syncfusion_flutter_charts: ^25.1.41+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
